import random; player = int(input('Rock(1), Paper(2), or Scissors(3) - Choose One: '))
computer = random.randint(1, 3)
print("Computer Chose", ["Rock", "Paper", "Scissors"][computer - 1])
if player == computer: print("Tie")
elif (player - computer) % 3 == 1: print("Player Wins!")
else: print("Robot Wins!")
